server:
  port: 8080
  tomcat:
    threads:
      max: 2        # ? Limit max threads to 10
      min-spare: 1


spring:
  application:
    name: task-management

  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:taskdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
        maximum-pool-size: 2  # Simulate DB pool exhaustion


